---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.1.0"
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: check-toml
      - id: check-yaml
        args:
          - --allow-multiple-documents
          - --unsafe
  - repo: local
    hooks:
      - id: yapf
        name: yapf
        entry: yapf
        language: system
        files: \.py$
        args: ['-i "$@"']
      - id: isort
        name: isort
        entry: isort
        language: system
        files: \.py$
        args: ['"$@"']
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        args: [
          '--ignore=D413,W503,D107,D301,C101,C901,E800',
        ]
        files: \.py$
