---
name: Publish

"on":
  push:
    branches:
      - main

jobs:
  build-and-publish:
    if: github.repository == 'mom1/api-client-pydantic'
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
      - name: Install poetry
        run: make poetry-download
      - name: Install Semantic Release
        run: >-
          npm install --location=global
          semantic-release@21.1.2
          @semantic-release/changelog
          @semantic-release/git
          @semantic-release/exec
          @semantic-release/github
          semantic-release-gitmoji@1.5.0
      - name: Release package
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
